baseURL = "https://chenatu.github.io/"
title   = "Tech Notes"
languageCode = "en-us"


[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  defaultTheme = "auto"        # 跟随系统深浅色
  showCodeCopyButtons = true   # 代码块一键复制

[markup]
  [markup.highlight]
    style = "dracula"          # 程序员友好的高对比配色

